export const ErrorCode = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_FILE: 'INVALID_FILE',
  PARSE_ERROR: 'PARSE_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  ALREADY_INVITED: 'ALREADY_INVITED',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
